// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCYUbKa-Dlw47b3tkEyfhSAuUtYDsNk4',
    appId: '1:442379329561:web:449845a6a215c8729b4a88',
    messagingSenderId: '442379329561',
    projectId: 'taskly-7b969',
    authDomain: 'taskly-7b969.firebaseapp.com',
    storageBucket: 'taskly-7b969.firebasestorage.app',
    measurementId: 'G-15CZXTE81K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6uVJ_tTob8QRIliDV24smNof9fIjVFJM',
    appId: '1:442379329561:android:ccfbf7439b9bc4f59b4a88',
    messagingSenderId: '442379329561',
    projectId: 'taskly-7b969',
    storageBucket: 'taskly-7b969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX8aFW06vQJ7FgpCoqjGp6bp3-fFN2LF8',
    appId: '1:442379329561:ios:789ede4f5be2e34b9b4a88',
    messagingSenderId: '442379329561',
    projectId: 'taskly-7b969',
    storageBucket: 'taskly-7b969.firebasestorage.app',
    iosBundleId: 'com.vhx.taskly',
  );

}